# Neuroconductor Template
# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

environment:
  global:
    USE_RTOOLS: true    
    R_CHECK_INSTALL_ARGS: "--install-args=--build --no-multiarch"
    WARNINGS_ARE_ERRORS: 1

install:
  - ps: Bootstrap
  - ps: (new-object net.webclient).DownloadFile('https://sourceforge.net/projects/mcmc-jags/files/JAGS/4.x/Windows/JAGS-4.2.0-Rtools33.exe', 'C:\projects\JAGS-4.2.0.exe')
  - cmd: C:\projects\JAGS-4.2.0.exe /S  

matrix:
  - R_VERSION: devel

  - R_VERSION: release

  - R_VERSION: oldrel
    CRAN: http://cran.rstudio.com

  - R_VERSION: 3.3.0
    CRAN: http://cran.rstudio.com

  - R_VERSION: 3.2.0
    CRAN: http://cran.rstudio.com

cache:
  - C:\RLibrary

# Adapt as necessary starting from here
build_script:
  - travis-tool.sh install_deps

test_script:
  - mkdir -p C:\rtm
  - set TMP=C:/rtm
  - set TEMP=C:/rtm
  - set TMPDIR=C:/rtm
  # need to move to higher dir because CMake path req
  - mkdir -p C:\run
  - cp -avr * C:\run
  # need the tool a level above
  - cp ../travis-tool.sh C:\
  - cd C:\run
  # setting PATH to be specific - no MinGW overall - just R's
  - set PATH=C:\Rtools\bin;C:\Rtools\MinGW\bin;
  - set PATH=%PATH%;C:\Rtools\mingw_64\bin;
  - set PATH=%PATH%;C:\Program Files\Git\cmd;
  - set PATH=%PATH%;C:\Program Files (x86)\CMake\bin;
  - set PATH=%PATH%;"C:\Program Files (x86)\CMake\bin";
  - set PATH=%PATH%;C:\R\bin\i386;  
  - set PATH=%PATH%;C:\Program Files\Git\usr\bin  
  - set PATH=%PATH%;C:\Users\appveyor\AppData\Roaming\npm
  - set PATH=%PATH%;C:\Users\appveyor\AppData\Local\Yarn\bin
  - set PATH=%PATH%;C:\Program Files\AppVeyor\BuildAgent\
  - set PATH=%PATH%;C:\Windows\system32
  - set PATH=%PATH%;C:\Windows
  - set PATH=%PATH%;C:\Windows\System32\Wbem
  - set PATH=%PATH%;C:\Windows\System32\WindowsPowerShell\v1.0\
  - set PATH=%PATH%;C:\Program Files\7-Zip
  - travis-tool.sh run_tests
  - ls
  - ls ../
  # - cp ../*.zip ./
  - cp -r C:/run/* %APPVEYOR_BUILD_FOLDER%
  - cd %APPVEYOR_BUILD_FOLDER%

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.zip'
    name: Bits

before_deploy:
  - PKG_TARBALL=$(ls -1t *.zip | head -n 1); 
  - PKG_TARBALL_WITH_R=`echo $PKG_TARBALL | sed 's/.zip/_'"R${rver}"'.zip/'` ;
  - mv ${PKG_TARBALL} ${PKG_TARBALL_WITH_R} ;

deploy:
  provider: GitHub
  description: 'Windows Binary'
  auth_token:
    secure: ${NEUROCKEY}
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
